//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 31/12/2008 12:23:27
// This source code was auto-generated by NHQG (NHQG), Version 2.0.0.0.
// 
namespace Query {
    using NHibernate = global::NHibernate;
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public static Root_Query_NavigationType NavigationType {
            get {
                return new Root_Query_NavigationType();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Query_NavigationType<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_NavigationType..ctor
            /// </summary>
            public Query_NavigationType() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_NavigationType..ctor
            /// </summary>
            public Query_NavigationType(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_NavigationType..ctor
            /// </summary>
            public Query_NavigationType(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_NavigationType.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Name", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NavigationType.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> IsLocked {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "IsLocked", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_NavigationType.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            public virtual Query_Collection_NavigationItems NavigationItems {
                get {
                    string temp = associationPath;
                    temp = (temp + ".NavigationItems");
                    return new Query_Collection_NavigationItems(this, "NavigationItems", temp);
                }
            }
            
            [System.CLSCompliantAttribute(false)]
            public class Query_Collection_NavigationItems : CollectionQueryBuilder<T1> {
                
                public Query_Collection_NavigationItems(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_Navigation<T1> With() {
                    Query_Navigation<T1> query = new Query_Navigation<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_Navigation<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_Navigation<T1> query = new Query_Navigation<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_Navigation<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_Navigation<T1> query = new Query_Navigation<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_Navigation<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_Navigation<T1> query = new Query_Navigation<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Root_Query_NavigationType : Query_NavigationType<Membrane.Models.NavigationManagement.NavigationType> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NavigationType {
            
            /// <summary>
            /// Query helper for member NavigationType.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.IsLocked
            /// </summary>
            public static OrderByClause IsLocked {
                get {
                    return new OrderByClause("IsLocked");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NavigationType {
            
            /// <summary>
            /// Query helper for member NavigationType.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.IsLocked
            /// </summary>
            public static PropertyProjectionBuilder IsLocked {
                get {
                    return new PropertyProjectionBuilder("IsLocked");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.NavigationType
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class NavigationType {
            
            /// <summary>
            /// Query helper for member NavigationType.Name
            /// </summary>
            public static NHibernate.Criterion.IProjection Name {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.IsLocked
            /// </summary>
            public static NHibernate.Criterion.IProjection IsLocked {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("IsLocked");
                }
            }
            
            /// <summary>
            /// Query helper for member NavigationType.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
