//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 31/12/2008 12:23:27
// This source code was auto-generated by NHQG (NHQG), Version 2.0.0.0.
// 
namespace Query {
    using NHibernate = global::NHibernate;
    
    
    public partial class Where {
        
        /// <summary>
        /// Query helper for member Where.Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public static Root_Query_Template Template {
            get {
                return new Root_Query_Template();
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Query_Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Query_Template<T1> : QueryBuilder<T1>
         {
            
            /// <summary>
            /// Query helper for member Query_Template..ctor
            /// </summary>
            public Query_Template() : 
                    this(null, "this", null) {
            }
            
            /// <summary>
            /// Query helper for member Query_Template..ctor
            /// </summary>
            public Query_Template(QueryBuilder<T1> parent, string name, string associationPath) : 
                    base(parent, name, associationPath) {
            }
            
            /// <summary>
            /// Query helper for member Query_Template..ctor
            /// </summary>
            public Query_Template(QueryBuilder<T1> parent, string name, string associationPath, bool backTrackAssociationOnEquality) : 
                    base(parent, name, associationPath, backTrackAssociationOnEquality) {
            }
            
            /// <summary>
            /// Query helper for member Query_Template.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Name {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Name", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Template.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Controller {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Controller", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Template.
            /// </summary>
            public virtual PropertyQueryBuilder<T1> Brail {
                get {
                    string temp = associationPath;
                    PropertyQueryBuilder<T1> child = new PropertyQueryBuilder<T1>(null, "Brail", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            /// <summary>
            /// Query helper for member Query_Template.
            /// </summary>
            public virtual IdQueryBuilder<T1> Id {
                get {
                    string temp = associationPath;
                    IdQueryBuilder<T1> child = new IdQueryBuilder<T1>(null, "Id", temp);
                    child.ShouldSkipJoinOnIdEquality = this.ShouldSkipJoinOnIdEquality;
                    return child;
                }
            }
            
            public virtual Query_Collection_PropertyBags PropertyBags {
                get {
                    string temp = associationPath;
                    temp = (temp + ".PropertyBags");
                    return new Query_Collection_PropertyBags(this, "PropertyBags", temp);
                }
            }
            
            [System.CLSCompliantAttribute(false)]
            public class Query_Collection_PropertyBags : CollectionQueryBuilder<T1> {
                
                public Query_Collection_PropertyBags(QueryBuilder<T1> parent, string name, string associationPath) : 
                        base(parent, name, associationPath) {
                }
                
                public virtual Query_PropertyBag<T1> With() {
                    Query_PropertyBag<T1> query = new Query_PropertyBag<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_PropertyBag<T1> With(NHibernate.SqlCommand.JoinType joinType) {
                    Query_PropertyBag<T1> query = new Query_PropertyBag<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = NHibernate.FetchMode.Default;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_PropertyBag<T1> With(NHibernate.FetchMode fetchMode) {
                    Query_PropertyBag<T1> query = new Query_PropertyBag<T1>(this, this.myName, this.associationPath);
                    query.joinType = NHibernate.SqlCommand.JoinType.InnerJoin;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
                
                public virtual Query_PropertyBag<T1> With(NHibernate.SqlCommand.JoinType joinType, NHibernate.FetchMode fetchMode) {
                    Query_PropertyBag<T1> query = new Query_PropertyBag<T1>(this, this.myName, this.associationPath);
                    query.joinType = joinType;
                    query.fetchMode = fetchMode;
                    query.ShouldSkipJoinOnIdEquality = true;
                    return query;
                }
            }
        }
        
        /// <summary>
        /// Query helper for member Where.Root_Query_Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Root_Query_Template : Query_Template<Membrane.Models.Content.Template> {
        }
    }
    
    public partial class OrderBy {
        
        /// <summary>
        /// Query helper for member OrderBy.Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Template {
            
            /// <summary>
            /// Query helper for member Template.Name
            /// </summary>
            public static OrderByClause Name {
                get {
                    return new OrderByClause("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Controller
            /// </summary>
            public static OrderByClause Controller {
                get {
                    return new OrderByClause("Controller");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Brail
            /// </summary>
            public static OrderByClause Brail {
                get {
                    return new OrderByClause("Brail");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Id
            /// </summary>
            public static OrderByClause Id {
                get {
                    return new OrderByClause("Id");
                }
            }
        }
    }
    
    public partial class ProjectBy {
        
        /// <summary>
        /// Query helper for member ProjectBy.Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Template {
            
            /// <summary>
            /// Query helper for member Template.Name
            /// </summary>
            public static PropertyProjectionBuilder Name {
                get {
                    return new PropertyProjectionBuilder("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Controller
            /// </summary>
            public static PropertyProjectionBuilder Controller {
                get {
                    return new PropertyProjectionBuilder("Controller");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Brail
            /// </summary>
            public static PropertyProjectionBuilder Brail {
                get {
                    return new PropertyProjectionBuilder("Brail");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Id
            /// </summary>
            public static NumericPropertyProjectionBuilder Id {
                get {
                    return new NumericPropertyProjectionBuilder("Id");
                }
            }
        }
    }
    
    public partial class GroupBy {
        
        /// <summary>
        /// Query helper for member GroupBy.Template
        /// </summary>
        [System.CLSCompliantAttribute(false)]
        public partial class Template {
            
            /// <summary>
            /// Query helper for member Template.Name
            /// </summary>
            public static NHibernate.Criterion.IProjection Name {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Name");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Controller
            /// </summary>
            public static NHibernate.Criterion.IProjection Controller {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Controller");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Brail
            /// </summary>
            public static NHibernate.Criterion.IProjection Brail {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Brail");
                }
            }
            
            /// <summary>
            /// Query helper for member Template.Id
            /// </summary>
            public static NHibernate.Criterion.IProjection Id {
                get {
                    return NHibernate.Criterion.Projections.GroupProperty("Id");
                }
            }
        }
    }
}
